{
 "title": "HAProxy Operator",
 "description": "HAProxy with Prometheus data",
 "tags": [
  "haproxy",
  "servers"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "lokids", "label": "Loki datasource", "query": "loki" },
   { "name": "prometheusds", "label": "Prometheus datasource", "query": "prometheus" },
   {
    "name": "juju_unit",
    "label": "Juju unit",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_application=~\"$juju_application\"},juju_unit)"
    }
   },
   {
    "name": "juju_application",
    "label": "Juju application",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\"},juju_application)"
    }
   },
   {
    "name": "juju_model_uuid",
    "label": "Juju model uuid",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\"},juju_model_uuid)"
    }
   },
   { "name": "juju_model", "label": "Juju model", "query": { "query": "label_values(up,juju_model)" } },
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(haproxy_process_nbproc,instance)"
    }
   },
   {
    "name": "backend",
    "label": "Backend",
    "query": {
     "query": "label_values(haproxy_backend_status{instance=\"$host\"}, proxy)"
    }
   },
   {
    "name": "frontend",
    "label": "Frontend",
    "query": {
     "query": "label_values(haproxy_frontend_status{instance=\"$host\"}, proxy)"
    }
   },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(haproxy_server_status{instance=\"$host\"}, server)"
    }
   },
   {
    "name": "code",
    "label": "HTTP Code",
    "query": {
     "query": "label_values(haproxy_frontend_http_responses_total{instance=\"$host\"}, code)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Basic General Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Number of HTTP status codes per interval",
     "type": "timeseries",
     "description": "The rate of backend responses is flipped along the time axis",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(code) (rate(haproxy_frontend_http_responses_total{code=~\"$code\",instance=\"$host\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",proxy=~\"$frontend\"}[$__rate_interval]))",
       "legendFormat": "Front {{ code }}"
      },
      {
       "expr": "sum by(code) (rate(haproxy_backend_http_responses_total{code=~\"$code\",instance=\"$host\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",proxy=~\"$backend\"}[$__rate_interval]))",
       "legendFormat": "Back {{ code }}"
      }
     ]
    },
    {
     "title": "Rate of Incoming / Outgoing bytes",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(instance) (rate(haproxy_frontend_bytes_in_total{instance=\"$host\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",proxy=~\"$frontend\"}[$__rate_interval]) * 8)",
       "legendFormat": "IN Front"
      },
      {
       "expr": "sum by(instance) (rate(haproxy_frontend_bytes_out_total{instance=\"$host\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",proxy=~\"$frontend\"}[$__rate_interval]) * 8)",
       "legendFormat": "OUT Front"
      },
      {
       "expr": "sum by(instance) (rate(haproxy_backend_bytes_in_total{instance=\"$host\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",proxy=~\"$backend\"}[$__rate_interval]) * 8)",
       "legendFormat": "IN Back"
      },
      {
       "expr": "sum by(instance) (rate(haproxy_backend_bytes_out_total{instance=\"$host\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",proxy=~\"$backend\"}[$__rate_interval]) * 8)",
       "legendFormat": "OUT Back"
      }
     ]
    },
    {
     "title": "Number of connections per interval",
     "type": "timeseries",
     "description": "The rate of backend connections is flipped along the time axis",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(instance) (rate(haproxy_frontend_connections_total{instance=\"$host\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",proxy=~\"$frontend\"}[$__rate_interval]))",
       "legendFormat": "Front"
      },
      {
       "expr": "sum by(instance) (rate(haproxy_backend_connection_errors_total{instance=\"$host\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",proxy=~\"$backend\"}[$__rate_interval]))",
       "legendFormat": "Back errors"
      }
     ]
    },
    {
     "title": "Number of requests and responses per interval",
     "type": "timeseries",
     "description": "The rate of backend requests/responses is flipped along the time axis",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(instance) (rate(haproxy_frontend_http_requests_total{instance=\"$host\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",proxy=~\"$frontend\"}[$__rate_interval]))",
       "legendFormat": "Front requests"
      },
      {
       "expr": "sum by(instance) (rate(haproxy_frontend_request_errors_total{instance=\"$host\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",proxy=~\"$frontend\"}[$__rate_interval]))",
       "legendFormat": "Front requests errors"
      },
      {
       "expr": "sum by(instance) (rate(haproxy_frontend_requests_denied_total{instance=\"$host\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",proxy=~\"$frontend\"}[$__rate_interval]))",
       "legendFormat": "Front request denied"
      },
      {
       "expr": "sum by(instance) (rate(haproxy_backend_redispatch_warnings_total{instance=\"$host\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",proxy=~\"$backend\"}[$__rate_interval]))",
       "legendFormat": "Back redispatch warnings"
      },
      {
       "expr": "sum by(instance) (rate(haproxy_backend_retry_warnings_total{instance=\"$host\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",proxy=~\"$backend\"}[$__rate_interval]))",
       "legendFormat": "Back retry warnings"
      },
      {
       "expr": "sum by(instance) (rate(haproxy_backend_response_errors_total{instance=\"$host\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",proxy=~\"$backend\"}[$__rate_interval]))",
       "legendFormat": "Back response errors"
      },
      {
       "expr": "sum by(instance) (haproxy_backend_current_queue{instance=\"$host\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",proxy=~\"$backend\"})",
       "legendFormat": "Back queued requests"
      },
      {
       "expr": "sum by(instance) (rate(haproxy_backend_http_requests_total{instance=\"$host\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",proxy=~\"$backend\"}[$__rate_interval]))",
       "legendFormat": "Back requests"
      }
     ]
    },
    {
     "title": "Number of active sessions per interval",
     "type": "timeseries",
     "description": "The rate of active backend sessions is flipped along the time axis",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(instance) (haproxy_frontend_current_sessions{instance=\"$host\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",proxy=~\"$frontend\"})",
       "legendFormat": "Front"
      },
      {
       "expr": "sum by(instance) (haproxy_backend_current_sessions{instance=\"$host\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",proxy=~\"$frontend\"})",
       "legendFormat": "Back"
      }
     ]
    },
    {
     "title": "Backend: Queued requests not assigned to any server",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_backend_current_queue{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "Queued {{ proxy }}"
      }
     ]
    },
    {
     "title": "Backend: Max queued requests not assigned to any server",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_backend_max_queue{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "Max {{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Basic General Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Number of UP frontend and backend",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 22, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count(haproxy_frontend_status{instance=\"$host\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"} == 1)",
       "legendFormat": "Front Up"
      },
      {
       "expr": "count(haproxy_backend_status{instance=\"$host\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"} == 1)",
       "legendFormat": "Back Up"
      }
     ]
    },
    {
     "title": "Started...",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 22, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - haproxy_process_start_time_seconds{instance=\"$host\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Throughtput / Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Front - Incoming / Outgoing bytes",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "targets": [
      {
       "expr": "rate(haproxy_frontend_bytes_in_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])*8",
       "legendFormat": "IN {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_frontend_bytes_out_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])*8",
       "legendFormat": "OUT {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Incoming / Outgoing bytes",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_bytes_in_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])*8",
       "legendFormat": "IN {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_backend_bytes_out_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])*8",
       "legendFormat": "OUT {{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Connections successful / denied",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_frontend_connections_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Successful {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_frontend_denied_connections_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Denied {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Connections attempts / errors",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_connection_attempts_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Attempts {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_backend_connection_errors_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Error {{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Maximum observed number of connections per second",
     "type": "timeseries",
     "description": "The maximum number of connections per second received by each of the haproxy frontends",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_frontend_connections_rate_max{proxy=~\"$frontend\",instance=\"$host\"}",
       "legendFormat": "Max {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Connections reuses",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_connection_reuses_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Reuses {{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests / Responses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Back - HTTP requests OK / Denied",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_http_requests_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Total {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_backend_requests_denied_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Denied {{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - HTTP requests OK / Error / Denied",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_frontend_http_requests_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Total {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_frontend_request_errors_total{proxy=~\"$frontend\", instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Error {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_frontend_requests_denied_total{proxy=~\"$frontend\", instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Denied {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - HTTP responses denied",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_responses_denied_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Denied {{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - HTTP responses denied",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_frontend_responses_denied_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Denied {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Error / Redispatch / Retry",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_redispatch_warnings_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Redispatch {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_backend_retry_warnings_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Retry {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_backend_response_errors_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Error {{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Maximum observed number of HTTP requests per second",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_frontend_http_requests_rate_max{proxy=~\"$frontend\", instance=\"$host\"}",
       "legendFormat": "Max {{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Back - Avg connection time",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_backend_connect_time_average_seconds{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Max connection time",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_backend_max_connect_time_seconds{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Avg. total time",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_backend_total_time_average_seconds{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Max total time",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_backend_max_total_time_seconds{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Avg. response time",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_backend_response_time_average_seconds{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Max response time",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_backend_max_response_time_seconds{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Avg. queue time for last 1024 successful connections",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_backend_queue_time_average_seconds{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Max queue time",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_backend_max_queue_time_seconds{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Responses by HTTP code",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Front - HTTP responses code",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_frontend_http_responses_total{proxy=~\"$frontend\", code=~\"$code\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ code }} {{ proxy }} "
      }
     ]
    },
    {
     "title": "Back - HTTP responses code",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_http_responses_total{proxy=~\"$backend\", code=~\"$code\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ code }} {{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - HTTP responses code",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_http_responses_total{proxy=~\"$backend\",server=~\"$server\",code=~\"$code\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ code }} {{ proxy }} {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Front - Number of sessions",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_frontend_sessions_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Total {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_frontend_denied_sessions_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Denied {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Number of sessions",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_sessions_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Total {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Maximum observed number of active sessions and limit",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_backend_max_sessions{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "Max {{ proxy }}"
      },
      {
       "expr": "haproxy_backend_limit_sessions{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "Limit {{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Maximum observed number of active sessions and limit",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_frontend_max_sessions{proxy=~\"$frontend\",instance=\"$host\"}",
       "legendFormat": "Max {{ proxy }}"
      },
      {
       "expr": "haproxy_frontend_limit_sessions{proxy=~\"$frontend\",instance=\"$host\"}",
       "legendFormat": "Limit {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Maximum observed number of sessions per second",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_backend_max_session_rate{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "Max {{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Maximum observed number of sessions per second and limit",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_frontend_max_session_rate{proxy=~\"$frontend\",instance=\"$host\"}",
       "legendFormat": "Max {{ proxy }}"
      },
      {
       "expr": "haproxy_frontend_limit_session_rate{proxy=~\"$frontend\",instance=\"$host\"}",
       "legendFormat": "Limit {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Failed header rewriting warnings",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_failed_header_rewriting_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Failed header rewriting warnings",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_frontend_failed_header_rewriting_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back -  Last session assigned",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_last_session_seconds{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Maximum observed number of HTTP requests per second",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_frontend_http_requests_rate_max{proxy=~\"$frontend\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back -  Data transfers aborted",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_client_aborts_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "By client {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_backend_server_aborts_total{proxy=~\"$frontend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "By server {{ proxy }}"
      }
     ]
    },
    {
     "title": "Server -  Data transfers aborted",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_server_client_aborts_total{proxy=~\"$frontend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "By client {{ proxy }} / {{ server }}"
      },
      {
       "expr": "haproxy_server_server_aborts_total{proxy=~\"$frontend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "By server {{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Health and Weight",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Back - UP->DOWN transitions",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_check_up_down_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Service weight",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_backend_weight{proxy=~\"$backend\", instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Service user weight",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_backend_uweight{proxy=~\"$backend\", instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Front - Status",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_frontend_status{proxy=~\"$frontend\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Status",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_backend_status{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Internal errors",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_frontend_internal_errors_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Internal errors",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_internal_errors_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Active servers",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_backend_active_servers{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Backup servers",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_backend_backup_servers{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By server - Throughtput  / Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Server - Incoming / Outgoing bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_bytes_in_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])*8",
       "legendFormat": "IN {{ proxy }} / {{ server }}"
      },
      {
       "expr": "rate(haproxy_server_bytes_out_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])*8",
       "legendFormat": "OUT {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Connections",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_used_connections_current{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "In use {{ proxy }} / {{ server }}{{ proxy }}"
      },
      {
       "expr": "rate(haproxy_server_idle_connections_current{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Estimated {{ proxy }} / {{ server }}{{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - Connections attempts / error",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_connection_attempts_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Attempts {{ proxy }} / {{ server }}"
      },
      {
       "expr": "rate(haproxy_server_connection_errors_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Error {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Number of connections reuses",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_connection_reuses_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Reuses {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Idle connections",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_idle_connections_current{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Available idle connections {{ proxy }} / {{ server }}"
      },
      {
       "expr": "rate(haproxy_server_idle_connections_limit{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Limit available idle connections {{ proxy }} / {{ server }}{{ proxy }}"
      },
      {
       "expr": "rate(haproxy_server_safe_idle_connections_current{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Number of safe idle connections {{ proxy }} / {{ server }}{{ proxy }}"
      },
      {
       "expr": "rate(haproxy_server_unsafe_idle_connections_current{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Number of unsafe idle connections {{ proxy }} / {{ server }}{{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By server - Requests / Responses / Queues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Server - HTTP responses denied",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_responses_denied_total{proxy=~\"$backend\", instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Denied {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Error / Redispatch / Retry",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_redispatch_warnings_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Redispatch {{ proxy }} / {{ server }}"
      },
      {
       "expr": "rate(haproxy_server_retry_warnings_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Retry {{ proxy }} / {{ server }}"
      },
      {
       "expr": "rate(haproxy_server_response_errors_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Error {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Queued requests",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_current_queue{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Current {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Max  queued requests and limit",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_server_max_queue{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "Max {{ proxy }} / {{ server }}"
      },
      {
       "expr": "haproxy_server_queue_limit{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "Limit {{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By server - Times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Server - Average connection time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_server_connect_time_average_seconds{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Max connection time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_server_max_connect_time_seconds{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Average response time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_server_response_time_average_seconds{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Max response time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_server_max_response_time_seconds{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Average total time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_server_total_time_average_seconds{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Max total time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_server_max_total_time_seconds{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Average queue time for last 1024 successful connections",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_queue_time_average_seconds{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Max queue time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_max_queue_time_seconds{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By server - Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Server - Number of active sessions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_sessions_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Total {{ proxy }} / {{ server }}"
      },
      {
       "expr": "haproxy_server_limit_sessions{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "Limit {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Failed header rewriting warnings",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_failed_header_rewriting_total{proxy=~\"$frontend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }} /  {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Number of sessions per second and limit",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_server_max_session_rate{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "Rate {{ proxy }} / {{ server }}"
      },
      {
       "expr": "haproxy_server_limit_session_rate{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "Limit {{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By server - Health and Weight",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Server - Service weight",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "haproxy_server_weight{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Users weight",
     "type": "timeseries",
     "description": "Server's user weight, or sum of active servers' user weights for a backend",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "haproxy_server_uweight{proxy=~\"$backend\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - UP->DOWN transitions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_check_up_down_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Checks failures",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_check_failures_total{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Checks duration",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_server_check_duration_seconds{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server -Throttle percentage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "haproxy_server_current_throttle{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Number of seconds since last session assigned to server/backend",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_last_session_seconds{proxy=~\"$backend\", server=~\"$server\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By server - Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Server - Status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_server_status{proxy=~\"$backend\",server=~\"$server\",instance=\"$host\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Internal errors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_internal_errors_total{proxy=~\"$backend\",instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - Failed DNS resolutions",
     "type": "timeseries",
     "description": "Number of failed DNS resolutions in current worker process since started",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_process_failed_resolutions{instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Failed"
      }
     ]
    }
   ]
  },
  {
   "title": "Process Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Process - Memory",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "haproxy_process_max_memory_bytes{instance=\"$host\"}",
       "legendFormat": "Per-process memory limit (in bytes); 0=unset"
      },
      {
       "expr": "rate(haproxy_process_pool_allocated_bytes{instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Total amount of memory allocated in pools (in bytes)"
      },
      {
       "expr": "rate(haproxy_process_pool_used_bytes{instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Total amount of memory used in pools (in bytes)"
      }
     ]
    },
    {
     "title": "Process - Tasks",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_process_current_tasks{instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Current number of tasks"
      },
      {
       "expr": "haproxy_process_current_run_queue{instance=\"$host\"}",
       "legendFormat": "Current number of tasks in the run-queue"
      },
      {
       "expr": "haproxy_process_stopping{instance=\"$host\"}",
       "legendFormat": "Non zero means stopping in progress"
      }
     ]
    },
    {
     "title": "Process - Maximum open files / sockets",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_max_fds{instance=\"$host\"}",
       "legendFormat": "Maximum number of open file descriptors; 0=unset"
      },
      {
       "expr": "haproxy_process_max_sockets{instance=\"$host\"}",
       "legendFormat": "Maximum number of open sockets"
      }
     ]
    },
    {
     "title": "Process - Pipes",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_max_pipes{instance=\"$host\"}",
       "legendFormat": "Configured maximum number of pipes"
      },
      {
       "expr": "rate(haproxy_process_pipes_used_total{instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Number of pipes in used"
      },
      {
       "expr": "rate(haproxy_process_pipes_free_total{instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Number of pipes unused"
      }
     ]
    },
    {
     "title": "Process - Configured threads / processes",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_nbthread{instance=\"$host\"}",
       "legendFormat": "Threads"
      },
      {
       "expr": "haproxy_process_nbproc{instance=\"$host\"}",
       "legendFormat": "Processes"
      }
     ]
    },
    {
     "title": "Process - Pool allocations",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_pool_failures_total{instance=\"$host\"}",
       "legendFormat": "Total number of failed pool allocations"
      }
     ]
    },
    {
     "title": "Process - Idle",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "haproxy_process_idle_time_percent{instance=\"$host\"}",
       "legendFormat": "Idle to total ratio over last sample (percent)"
      }
     ]
    },
    {
     "title": "Process - Jobs",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_process_jobs{instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Current number of active jobs (listeners, sessions, open devices)"
      },
      {
       "expr": "rate(haproxy_process_unstoppable_jobs{instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Current number of active jobs that can't be stopped during a soft stop"
      },
      {
       "expr": "rate(haproxy_process_listeners{instance=\"$host\"}[$__rate_interval])",
       "legendFormat": "Current number of active listeners"
      }
     ]
    },
    {
     "title": "Process - Peers",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_active_peers{instance=\"$host\"}",
       "legendFormat": "Current number of active peers"
      },
      {
       "expr": "haproxy_process_connected_peers{instance=\"$host\"}",
       "legendFormat": "Current number of connected peers"
      }
     ]
    },
    {
     "title": "Process - Logs",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_dropped_logs_total{instance=\"$host\"}",
       "legendFormat": "Total number of dropped logs"
      },
      {
       "expr": "haproxy_process_recv_logs_total{instance=\"$host\"}",
       "legendFormat": "Total number of log messages received by log-forwarding listeners"
      }
     ]
    },
    {
     "title": "Process - Bytes out",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "targets": [
      {
       "expr": "rate(haproxy_process_bytes_out_total{instance=\"$host\"}[$__rate_interval])*8",
       "legendFormat": "Emitted by current worker {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_process_spliced_bytes_out_total{instance=\"$host\"}[$__rate_interval])*8",
       "legendFormat": "Emitted by current worker through a kernel pipe {{ proxy }}"
      }
     ]
    },
    {
     "title": "Process - Uptime",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_process_uptime_seconds{instance=\"$host\"}",
       "legendFormat": "How long ago this worker process was started"
      }
     ]
    }
   ]
  },
  { "title": "Traffic Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Top 10 IPs per requests per second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "topk(10,sum by(ip)(rate({filename=\"/var/log/haproxy.log\", juju_application=~\"$juju_application\", juju_model=~\"$juju_model\", juju_model_uuid=~\"$juju_model_uuid\", juju_unit=~\"$juju_unit\"} | regexp \"haproxy\\\\[\\\\d+\\\\]: (?P<ip>.*):(?P<port>\\\\d+) .* (?P<status_code>\\\\d+) (?P<bytes_sent>\\\\d+) - - .* \\\"(?P<method>\\\\w+) (?P<uri>\\\\S+)\" | ip!=\"\" | __error__=\"\"[5m])))"
    }
   ]
  },
  {
   "title": "Top 10 IPs per bytes per second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 60 },
   "targets": [
    {
     "expr": "topk(10,sum by(ip)(rate({filename=\"/var/log/haproxy.log\", juju_application=~\"$juju_application\", juju_model=~\"$juju_model\", juju_model_uuid=~\"$juju_model_uuid\", juju_unit=~\"$juju_unit\"} | regexp \"haproxy\\\\[\\\\d+\\\\]: (?P<ip>.*):(?P<port>\\\\d+) .* (?P<status_code>\\\\d+) (?P<bytes>\\\\d+) - - .* \\\"(?P<method>\\\\w+) (?P<uri>\\\\S+)\" | unwrap bytes | __error__=\"\"[5m])))"
    }
   ]
  },
  {
   "title": "Top 10 paths queried per second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 60 },
   "targets": [
    {
     "expr": "topk(10,sum by(uri)(rate({filename=\"/var/log/haproxy.log\", juju_application=~\"$juju_application\", juju_model=~\"$juju_model\", juju_model_uuid=~\"$juju_model_uuid\", juju_unit=~\"$juju_unit\"} | regexp \"haproxy\\\\[\\\\d+\\\\]: (?P<ip>.*):(?P<port>\\\\d+) .* (?P<status_code>\\\\d+) (?P<bytes>\\\\d+) - - .* \\\"(?P<method>\\\\w+) (?P<uri>\\\\S+)\" | unwrap bytes | __error__=\"\"[5m])))",
     "legendFormat": "path={{uri}}"
    }
   ]
  }
 ]
}