# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

"""haproxy-operator charm tls information."""

import json
import logging
import typing
from dataclasses import dataclass

import ops
from charmlibs.interfaces.tls_certificates import (
    Certificate,
    TLSCertificatesRequiresV4,
)
from charms.haproxy.v2.haproxy_route import valid_domain_with_wildcard
from pydantic import ValidationError
from pydantic.dataclasses import dataclass as pydantic_dataclass

logger = logging.getLogger()

HAPROXY_PEER_RELATION = "haproxy-peers"
# Disable bandit since this is not hardcoded credentials.
SHARED_PRIVATE_KEY_SECRET_LABEL = "haproxy-shared-private-key"  # nosec


class TLSNotReadyError(Exception):
    """Exception raised when the charm is not ready to handle TLS."""


class PeerRelationNotFoundError(Exception):
    """Exception raised when the peer relation is not found."""


class PrivateKeyNotFoundError(Exception):
    """Exception raised when the private key is not found."""


class SharedTLSInformationNotFoundError(Exception):
    """Exception raised when the shared private key is not found in the peer relation."""


@pydantic_dataclass(frozen=True, config={"arbitrary_types_allowed": True})
class HaproxyPeerRelationAppData:
    """A dataclass to represent a certificate and its chain.

    Attributes:
        shared_certificates: A list of tuples, each containing a certificate and its associated chain.
    """

    shared_certificates: list[tuple[Certificate, list[Certificate]]]


def haproxy_peer_relation_app_data_encoder(value: typing.Any) -> str:
    """Encoder function to convert shared_certificates list into a JSON string for relation data."""
    return json.dumps(
        [
            {
                "certificate": str(cert),
                "chain": [str(c) for c in chain],
            }
            for cert, chain in value
        ]
    )


def haproxy_peer_relation_app_data_decoder(
    value: str,
) -> list[tuple[Certificate, list[Certificate]]]:
    """Decoder function to convert a JSON string from relation data into shared_certificates list."""
    decoded = json.loads(value)
    return [
        (
            Certificate.from_string(item["certificate"]),
            [Certificate.from_string(cert) for cert in item["chain"]],
        )
        for item in decoded
    ]


# pydantic dataclass is not used here as we already performed our validation logic
# in the validate method
@dataclass(frozen=True)
class TLSInformation:
    """A component of charm state containing information about TLS.

    Attributes:
        hostnames: Configured external hostname.
        tls_cert_and_ca_chain: A list of tuples, each containing a certificate obtained from the relation and the Certificate chain.
        private_key: Private key used to generate the CSR.
    """

    hostnames: list[str]
    tls_cert_and_ca_chain: HaproxyPeerRelationAppData
    private_key: str

    @classmethod
    def from_charm(
        cls,
        charm: ops.CharmBase,
        certificates: TLSCertificatesRequiresV4,
        allow_no_certificates: bool = False,
    ) -> "TLSInformation":
        """Get TLS information from a charm instance.

        Args:
            charm: The haproxy charm.
            certificates: TLS certificates requirer class.
            allow_no_certificates: If the charm can proceed without requesting any certificates.

        Raises:
            PrivateKeyNotFoundError: When waiting for the private key to be generated.

        Returns:
            TLSInformation: Information about configured TLS certs.
        """
        cls.validate(charm, certificates, allow_no_certificates)

        hostnames = [
            certificate_request.common_name
            for certificate_request in certificates.certificate_requests
        ]

        if not charm.unit.is_leader():
            return cls._from_peer_relation(charm, hostnames, allow_no_certificates)
        provider_certificates, private_key = certificates.get_assigned_certificates()
        if not private_key and not allow_no_certificates:
            logger.error(
                "Private key not found while trying to get assigned certificates."
                "The private key should have already been generated by the charm when creating the CSRs."
            )
            raise PrivateKeyNotFoundError("Private key not found.")

        return cls(
            hostnames=hostnames,
            tls_cert_and_ca_chain=HaproxyPeerRelationAppData(
                shared_certificates=[
                    (certificate.certificate, certificate.chain)
                    for certificate in provider_certificates
                ]
            ),
            private_key=str(private_key),
        )

    @classmethod
    def _from_peer_relation(
        cls, charm: ops.CharmBase, hostnames: list[str], allow_no_certificates: bool
    ) -> "TLSInformation":
        """Get TLS information from peer relation for non-leader unit."""
        peer_relation = charm.model.get_relation(HAPROXY_PEER_RELATION)
        if peer_relation is None:
            logger.error("Peer relation not found while trying to get TLS information.")
            raise PeerRelationNotFoundError("Waiting for peer relation.")
        try:
            peer_relation_data = peer_relation.load(
                HaproxyPeerRelationAppData,
                charm.app,
                decoder=haproxy_peer_relation_app_data_decoder,
            )
            private_key_secret = charm.model.get_secret(label=SHARED_PRIVATE_KEY_SECRET_LABEL)
            private_key = private_key_secret.get_content(refresh=True).get("private-key")
        except (ops.SecretNotFoundError, ValidationError) as exc:
            logger.error("Shared private key secret not found in the model.")
            if not allow_no_certificates:
                raise SharedTLSInformationNotFoundError(
                    "Waiting for shared private key secret."
                ) from exc
            return cls(
                hostnames=hostnames,
                tls_cert_and_ca_chain=HaproxyPeerRelationAppData(shared_certificates=[]),
                private_key="",
            )
        return cls(
            hostnames=hostnames,
            tls_cert_and_ca_chain=peer_relation_data,
            private_key=str(private_key),
        )

    # Validation is done in this method instead of using a pydantic model because
    # there are cases where we need to validate the state but we don't need the state instance.
    @classmethod
    def validate(
        cls,
        charm: ops.CharmBase,
        certificates: TLSCertificatesRequiresV4,
        allow_no_certificates: bool = False,
    ) -> None:
        """Validate the precondition to initialize this state component.

        Args:
            charm: The haproxy charm.
            certificates: TLS certificates requirer class.
            allow_no_certificates: If the charm can proceed without requesting any certificates.

        Raises:
            TLSNotReadyError: if the charm is not ready to handle TLS.
        """
        tls_requirer_integration = charm.model.get_relation(certificates.relationship_name)
        if allow_no_certificates:
            logger.warning("Allowing load balancing without requesting TLS certificates.")

        if not certificates.certificate_requests and not allow_no_certificates:
            logger.error(
                "The charm did not request any certificates."
                "You need to either set the `external-hostname` config or request a hostname from"
                "one of the requirer databag."
            )
            raise TLSNotReadyError(
                "No hostname configured or requested. See juju debug-log for details."
            )

        if invalid_hostname := [
            certificate_request.common_name
            for certificate_request in certificates.certificate_requests
            if not valid_domain_with_wildcard(certificate_request.common_name)
        ]:
            logger.error(
                (
                    "Some requested hostname(s) (%s) are not valid."
                    " Hostnames must be RFC-1138 compliant and can include"
                    " a wildcard."
                ),
                ",".join(invalid_hostname),
            )
            raise TLSNotReadyError("Some requested hostname(s) are not valid.")

        if (
            tls_requirer_integration is None
            or tls_requirer_integration.data.get(charm.app) is None
        ) and not allow_no_certificates:
            logger.error("Relation or relation data not ready.")
            raise TLSNotReadyError("Certificates relation or relation data not ready.")
