#!/usr/bin/env python3

# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

"""haproxy-route-policy-operator charm."""

import logging
import secrets
from typing import Any

import ops
from charmlibs.snap import SnapError
from charms.data_platform_libs.v0.data_interfaces import (
    DatabaseRequires,
)

from policy import (
    HaproxyRoutePolicyDatabaseMigrationError,
    configure_snap,
    create_or_update_user,
    install_snap,
    run_migrations,
    start_gunicorn_service,
)
from state.database import (
    DatabaseInformation,
    DatabaseRelationMissingError,
    DatabaseRelationNotReadyError,
)

logger = logging.getLogger(__name__)

DATABASE_RELATION = "database"
HAPROXY_ROUTE_POLICY_PORT = 8080
# Ignore bandit warnings here as these are labels
DJANGO_SECRET_KEY_SECRET_LABEL = "django-secret-key"  # nosec
DJANGO_ADMIN_CREDENTIALS_SECRET_LABEL = "django-admin-credentials"  # nosec
PEER_RELATION_NAME = "haproxy-route-policy-peer"


class DjangoSecretKeyMissingError(Exception):
    """Raised when the Django secret key is not generated by the leader unit."""


class DjangoAdminCredentialsMissingError(Exception):
    """Raised when the Django admin credentials are not generated by the leader unit."""


class HaproxyRoutePolicyCharm(ops.CharmBase):
    """Charm for HAProxy Route Policy service."""

    def __init__(self, *args: Any):
        super().__init__(*args)

        self.framework.observe(self.on.install, self._reconcile)
        self.framework.observe(self.on.upgrade_charm, self._reconcile)
        self.framework.observe(self.on.start, self._reconcile)
        self.framework.observe(self.on.config_changed, self._reconcile)
        self.framework.observe(
            self.on.get_admin_credentials_action, self._on_get_admin_credentials_action
        )
        self.framework.observe(self.on[PEER_RELATION_NAME].relation_joined, self._reconcile)
        self.framework.observe(self.on[PEER_RELATION_NAME].relation_changed, self._reconcile)

        self.database = DatabaseRequires(
            self,
            relation_name=DATABASE_RELATION,
            database_name=self.app.name,
            extra_user_roles="SUPERUSER",
        )
        self.framework.observe(self.database.on.database_created, self._reconcile)

    def _reconcile(self, _: ops.EventBase) -> None:
        """Reconcile snap configuration and service state."""
        peer_relation = self.model.get_relation(PEER_RELATION_NAME)
        if not peer_relation:
            self.unit.status = ops.WaitingStatus("Waiting for peer relation.")
            return

        try:
            install_snap()
            self.unit.status = ops.MaintenanceStatus("configuring haproxy-route-policy")
            database_information = DatabaseInformation.from_requirer(self, self.database)
            configure_snap(
                {
                    **self._get_django_secret_key(peer_relation),
                    **database_information.haproxy_route_policy_snap_configuration,
                }
            )
            self.unit.status = ops.MaintenanceStatus("running database migrations")
            run_migrations()

            self.unit.status = ops.MaintenanceStatus("Updating Django admin user.")
            username, password = self._get_django_admin_credentials(peer_relation).values()
            create_or_update_user(username, password)

            self.unit.status = ops.MaintenanceStatus("starting gunicorn service")
            start_gunicorn_service()

            self.unit.open_port("tcp", HAPROXY_ROUTE_POLICY_PORT)
        except (SnapError, HaproxyRoutePolicyDatabaseMigrationError) as exc:
            logger.exception("Failed to reconcile haproxy-route-policy service")
            self.unit.status = ops.BlockedStatus(f"reconciliation failed: {exc}")
            return
        except DatabaseRelationMissingError:
            self.unit.status = ops.BlockedStatus("Missing database relation.")
            return
        except DatabaseRelationNotReadyError:
            logger.exception("Database relation not ready")
            self.unit.status = ops.WaitingStatus("waiting for complete database relation.")
            return
        except (DjangoSecretKeyMissingError, DjangoAdminCredentialsMissingError):
            logger.exception("Django shared configuration not ready")
            self.unit.status = ops.WaitingStatus("Waiting for leader to set shared configuration.")
            return

        self.unit.status = ops.ActiveStatus()

    def _get_django_secret_key(self, peer_relation: ops.Relation) -> dict[str, str]:
        """Get the Django secret key from the charm's config.

        Returns:
            The Django secret key.

        Raises:
            DjangoSecretKeyMissingError: If the secret key is not yet created by the leader.
        """
        try:
            secret = self.model.get_secret(label=DJANGO_SECRET_KEY_SECRET_LABEL)
            return secret.get_content()
        except ops.SecretNotFoundError:
            if self.unit.is_leader():
                django_secret_key_data = {"secret-key": secrets.token_urlsafe(32)}
                secret = self.app.add_secret(
                    label=DJANGO_SECRET_KEY_SECRET_LABEL, content=django_secret_key_data
                )
                peer_relation.data[self.app]["django-secret-key"] = (
                    secret.label or DJANGO_SECRET_KEY_SECRET_LABEL
                )
                return django_secret_key_data
            raise DjangoSecretKeyMissingError(
                "Waiting for the leader unit to generate the Django secret key."
            )

    def _get_django_admin_credentials(self, peer_relation: ops.Relation) -> dict[str, str]:
        """Get the Django admin user from the charm's config.

        Returns:
            The Django admin user.
        """
        try:
            secret = self.model.get_secret(label=DJANGO_ADMIN_CREDENTIALS_SECRET_LABEL)
            return secret.get_content()
        except ops.SecretNotFoundError:
            if self.unit.is_leader():
                django_admin_credentials_data = {
                    "username": "admin",
                    "password": secrets.token_urlsafe(32),
                }
                secret = self.app.add_secret(
                    label=DJANGO_ADMIN_CREDENTIALS_SECRET_LABEL,
                    content=django_admin_credentials_data,
                )
                peer_relation.data[self.app]["django-admin-credentials"] = (
                    secret.label or DJANGO_ADMIN_CREDENTIALS_SECRET_LABEL
                )
                return django_admin_credentials_data
            raise DjangoAdminCredentialsMissingError(
                "Waiting for the leader unit to generate the Django admin credentials."
            )

    def _on_get_admin_credentials_action(self, event: ops.ActionEvent) -> None:
        """Handle the get-admin-credentials action."""
        try:
            secret = self.model.get_secret(
                label=DJANGO_ADMIN_CREDENTIALS_SECRET_LABEL
            ).get_content()
            event.set_results(
                {
                    "username": secret["username"],
                    "password": secret["password"],
                }
            )
            return
        except ops.SecretNotFoundError:
            event.fail("Admin credentials not found.")


if __name__ == "__main__":  # pragma: nocover
    ops.main(HaproxyRoutePolicyCharm)
