# Generated by Django 6.0.3 on 2026-03-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BackendRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("relation_id", models.IntegerField()),
                ("hostname_acls", models.JSONField(default=list)),
                ("backend_name", models.TextField()),
                ("paths", models.JSONField(default=list)),
                ("port", models.IntegerField()),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("pending", "pending"),
                            ("accepted", "accepted"),
                            ("rejected", "rejected"),
                        ],
                        db_index=True,
                        default="pending",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
