# Generated by Django 6.0.3 on 2026-03-19 12:58

import policy.db_models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BackendRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("relation_id", models.IntegerField()),
                (
                    "hostname_acls",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[policy.db_models.validate_hostname_acls],
                    ),
                ),
                ("backend_name", models.TextField(unique=True)),
                (
                    "paths",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[policy.db_models.validate_paths],
                    ),
                ),
                (
                    "port",
                    models.IntegerField(validators=[policy.db_models.validate_port]),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("pending", "pending"),
                            ("accepted", "accepted"),
                            ("rejected", "rejected"),
                        ],
                        db_index=True,
                        default="pending",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
