# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

# Generated by Django 6.0.3 on 2026-03-17 20:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.TextField(
                        choices=[
                            ("hostname_and_path_match", "hostname_and_path_match"),
                            ("match_request_id", "match_request_id"),
                        ]
                    ),
                ),
                ("value", models.JSONField()),
                (
                    "action",
                    models.TextField(choices=[("allow", "allow"), ("deny", "deny")]),
                ),
                ("priority", models.IntegerField(default=0)),
                ("comment", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
