# Generated by Django 6.0.4 on 2026-04-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policy", "0002_rule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="kind",
            field=models.TextField(
                choices=[
                    ("hostname_and_path_match", "hostname_and_path_match"),
                    ("backend_match", "backend_match"),
                ]
            ),
        ),
    ]
