#!/bin/sh

set -eu

apt-get -y update

juju-log 'Invoking charm-pre-install hooks'
[ -d exec.d ] && ( for f in exec.d/*/charm-pre-install; do [ -x $f ] && /bin/sh -c "$f"; done )

# Install missing python-yaml and python-apt packages
# Note that these depend on python2 on focal and newer
apt-get install -y python-yaml python-apt

juju-log 'Invoking python-based install hook'
# use python2 because python is 3 on focal or newer
python2 hooks/hooks.py install
