#!/bin/sh

set -eu

apt_get_install() {
    DEBIAN_FRONTEND=noninteractive apt-get -y -qq -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install $@
}

juju-log 'Invoking charm-pre-install hooks'
[ -d exec.d ] && ( for f in exec.d/*/charm-pre-install; do [ -x $f ] && /bin/sh -c "$f"; done )

DISTRIB_CODENAME=$(grep DISTRIB_CODENAME /etc/lsb-release | cut -d= -f2)
if [ "${DISTRIB_CODENAME}" = "focal" ]; then
    # Install missing python-yaml and python-apt packages
    apt-get install -y python2 python-yaml python-apt

    juju-log 'Invoking python-based install hook'
    python2 hooks/hooks.py install
else
    # Install missing python-yaml and python-apt packages
    apt-get install -y python-yaml python-apt

    juju-log 'Invoking python-based install hook'
    python hooks/hooks.py install
fi
