#!/bin/sh

# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

set -xe

# Create some directories
mkdir -p "$SNAP_DATA/app"

# set default configuration values
snapctl set debug='false'
snapctl set log-level='INFO'
