#!/bin/sh

# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

set -xe

# set default configuration values
snapctl set debug='false'
snapctl set log-level='INFO'
snapctl set allowed-hosts='["localhost", "127.0.0.1"]'
SECRET_KEY="$(tr -dc a-zA-Z0-9 < /dev/urandom | head -c 50)"
snapctl set secret-key="$SECRET_KEY"
