#!/usr/bin/env python3

# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

"""Charm state for database information."""

import json
import secrets
from typing import Annotated, cast

import ops
from pydantic import BeforeValidator, Field, IPvAnyAddress
from pydantic.dataclasses import dataclass
from validators import domain

# Ignore bandit warnings here as these are labels
DJANGO_SECRET_KEY_SECRET_LABEL = "django-secret-key"  # nosec
DJANGO_ADMIN_CREDENTIALS_SECRET_LABEL = "django-admin-credentials"  # nosec
PEER_RELATION_NAME = "haproxy-route-policy-peer"
SECRET_LENGTH = 32


class DjangoSecretKeyMissingError(Exception):
    """Raised when the Django secret key is not generated by the leader unit."""


class DjangoAdminCredentialsMissingError(Exception):
    """Raised when the Django admin credentials are not generated by the leader unit."""


class DjangoAdminCredentialsInvalidError(Exception):
    """Raised when the Django admin credentials are invalid."""


class PeerRelationMissingError(Exception):
    """Raised when the peer relation is missing."""


def valid_fqdn(value: str) -> str:
    """Validate if value is a valid fqdn. TLDs are not allowed.

    Raises:
        ValueError: When value is not a valid domain.

    Args:
        value: The value to validate.
    """
    if not bool(domain(value)):
        raise ValueError(f"Invalid domain: {value}")
    return value


FQDN = Annotated[str, BeforeValidator(valid_fqdn)]


@dataclass
class HaproxyRoutePolicyInformation:
    """Charm state for HAProxy Route Policy information.

    Attributes:
        allowed_hosts: List of allowed hosts.
        admin_username: Django admin username.
        admin_password: Django admin password.
        secret_key: Django secret key.
    """

    allowed_hosts: list[FQDN | IPvAnyAddress] = Field()
    admin_username: str = Field()
    admin_password: str = Field()
    secret_key: str = Field()

    @property
    def allowed_hosts_snap_configuration(self) -> dict[str, str]:
        """Return snap configuration keys and values."""
        return {
            "allowed-hosts": json.dumps([str(host) for host in self.allowed_hosts]),
        }

    @classmethod
    def from_charm(cls, charm: ops.CharmBase) -> "HaproxyRoutePolicyInformation":
        """Create a HaproxyRoutePolicyInformation charm state.

        Returns:
            HaproxyRoutePolicyInformation: The information.

        Raises:
            PeerRelationMissingError: If the peer relation is missing.
        """
        peer_relation = charm.model.get_relation(PEER_RELATION_NAME)
        if not peer_relation:
            raise PeerRelationMissingError("Peer relation is missing.")

        allowed_hosts = (
            [
                cast(IPvAnyAddress | FQDN, address)
                for address in cast(str, charm.config.get("allowed-hosts")).split(",")
            ]
            if charm.config.get("allowed-hosts")
            else []
        )
        credentials = _get_django_admin_credentials(charm, peer_relation)
        if not (credentials.get("username") and credentials.get("password")):
            raise DjangoAdminCredentialsInvalidError(
                "Waiting for the leader unit to generate the Django admin credentials."
            )
        secret_key = _get_django_secret_key(charm, peer_relation)["secret-key"]
        return cls(
            allowed_hosts=allowed_hosts,
            admin_username=credentials["username"],
            admin_password=credentials["password"],
            secret_key=secret_key,
        )


def _get_django_admin_credentials(
    charm: ops.CharmBase, peer_relation: ops.Relation
) -> dict[str, str]:
    """Get the Django admin user from the charm's config.

    Returns:
        The Django admin user.
    """
    try:
        secret = charm.model.get_secret(label=DJANGO_ADMIN_CREDENTIALS_SECRET_LABEL)
        return secret.get_content()
    except ops.SecretNotFoundError:
        if charm.unit.is_leader():
            django_admin_credentials_data = {
                "username": "admin",
                "password": secrets.token_urlsafe(SECRET_LENGTH),
            }
            secret = charm.app.add_secret(
                label=DJANGO_ADMIN_CREDENTIALS_SECRET_LABEL,
                content=django_admin_credentials_data,
            )
            peer_relation.data[charm.app]["django-admin-credentials"] = (
                secret.label or DJANGO_ADMIN_CREDENTIALS_SECRET_LABEL
            )
            return django_admin_credentials_data
        raise DjangoAdminCredentialsMissingError(
            "Waiting for the leader unit to generate the Django admin credentials."
        )


def _get_django_secret_key(
    charm: ops.CharmBase, peer_relation: ops.Relation
) -> dict[str, str]:
    """Get the Django secret key from the charm's config.

    Returns:
        The Django secret key.

    Raises:
        DjangoSecretKeyMissingError: If the secret key is not yet created by the leader.
    """
    try:
        secret = charm.model.get_secret(label=DJANGO_SECRET_KEY_SECRET_LABEL)
        return secret.get_content()
    except ops.SecretNotFoundError:
        if charm.unit.is_leader():
            django_secret_key_data = {
                "secret-key": secrets.token_urlsafe(SECRET_LENGTH)
            }
            secret = charm.app.add_secret(
                label=DJANGO_SECRET_KEY_SECRET_LABEL, content=django_secret_key_data
            )
            peer_relation.data[charm.app]["django-secret-key"] = (
                secret.label or DJANGO_SECRET_KEY_SECRET_LABEL
            )
            return django_secret_key_data
        raise DjangoSecretKeyMissingError(
            "Waiting for the leader unit to generate the Django secret key."
        )
