# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

name: Docs spread

on:
  pull_request:
  schedule:
  - cron: "0 15 * * SAT"

jobs:
  doc-test:
    uses: canonical/charm-ci/.github/workflows/doc-test.yml@v0.0.1-alpha.1
    permissions:
      contents: read
      actions: read
    with:
      spread-jobs-include: "docs-ci:*"
