name: Automated spread testing

on:
  workflow_dispatch:
  pull_request:
    # paths:
    # - 'docs/tutorial/getting-started.md'

jobs:
  docs-checks:
    uses: canonical/operator-workflows/.github/workflows/docs_spread.yaml@update-spread-package-name
    secrets: inherit
    with:
      input-file: docs/tutorial/getting-started.md
      output-dir: tests/spread/tutorial
      spread-job: github-ci:ubuntu-24.04:haproxy-operator/spread/
