# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

name: Integration tests

on:
  pull_request:
  schedule:
  - cron: "0 15 * * SAT"

jobs:
  integration-test:
    uses: canonical/charm-ci/.github/workflows/integration-test.yml@v0.0.1-alpha.1
    with:
      spread-jobs-include: "integration-test-ci:*"
    secrets: inherit
    permissions:
      contents: read
      packages: write
      actions: read
